enisdenjo/graphql-ws

.eslintrc.js, jest.config.js, package.json, src/message.ts, src/protocol.ts, src/server/index.ts, src/server/server.ts, src/tests/client.ts, src/tests/fixtures/simple.ts, src/tests/server.ts, src/types.d.ts, src/utils.ts, yarn.lock
This branch is based on the [protocol](https://github.com/enisdenjo/graphql-subscriptions-ws/tree/protocol) branch and implements the protocol described there.
=> feat(server): implement

package.json, src/client.ts, src/message.ts, src/tests/client.ts, src/tests/fixtures/simple.ts, src/types.d.ts, yarn.lock
This branch is based on the [server branch](https://github.com/enisdenjo/graphql-transport-ws/tree/server) and implements the protocol described in the [protocol branch](https://github.com/enisdenjo/graphql-transport-ws/tree/protocol).
=> feat(client): re-implement following the new protocol specification

src/client.ts, src/tests/client.ts, src/tests/fixtures/simple.ts, src/types.ts
Socky aims to introduce "concurrency" safety. Allows for sinks to subscribe/dispose in parallel while maintaining the WebSocket connection without races.
=> feat(client): introduce Socky 🧦 - the nifty internal socket state manager

src/client.ts, src/tests/client.ts
=> feat(client): Support providing custom WebSocket implementations

src/client.ts, src/server.ts, src/tests/client.ts, src/types.ts
=> feat(client): Optional `generateID` to provide subscription IDs

package.json, src/client.ts, src/tests/client.ts, src/tests/fixtures/simple.ts, src/tests/server.ts, yarn.lock
=> refactor(client): Stabilize and simplify tests

src/server.ts
When reviewing this, you might want to turn on the ignore whitespace differences setting.
- Handles the situation where timeouts are negative (which should disable them)
- Uses `isFinite` over `!== Infinity` (also handles NaN, etc)
- If the checks fail, uses `null` as the fallback, rather than `false`.
=> refactor: tweak types and checks for timeouts/intervals

.gitignore, README.md, package.json, rollup.config.js, tsconfig.build.json, tsconfig.cjs.json, tsconfig.esm.json, tsconfig.json, yarn.lock
=> feat: `cjs`, `esm` and `umd` builds with minification and compression for the browser

PROTOCOL.md, docs/interfaces/_message_.connectionackmessage.md, docs/interfaces/_server_.serveroptions.md, docs/modules/_client_.md, src/client.ts, src/message.ts, src/server.ts, src/tests/client.ts, src/tests/server.ts
=> feat: Send optional payload with the `ConnectionAck` message

README.md
I had to make the change below for the subscriptions to work properly in my case.
=> docs(recipe): fix Apollo example

docs/interfaces/_client_.clientoptions.md, src/client.ts, src/tests/client.ts
=> feat(client): Allow keeping the connection alive for some time before lazy closing

src/client.ts
=> fix(client): Stabilize and simplify internals

package.json
Closes https://github.com/enisdenjo/graphql-ws/issues/118
=> fix: Add `package.json` to exports map

docs/interfaces/client.clientoptions.md, docs/modules/client.md, src/client.ts, src/tests/client.ts
=> fix(client): Reduce WebSocket event listeners and add new `message` event for incoming messages

README.md, docs/README.md, docs/interfaces/use_fastify_websocket.extra.md, docs/modules/use_fastify_websocket.md, package.json, src/tests/use.ts, src/tests/utils/tservers.ts, src/use/fastify-websocket.ts, yarn.lock
```ts
import Fastify from 'fastify'; // yarn add fastify
import fastifyWebsocket from 'fastify-websocket'; // yarn add fastify-websocket
import { makeHandler } from 'graphql-ws/lib/use/fastify-websocket';
const fastify = Fastify();
fastify.register(fastifyWebsocket);
fastify.get(
'/graphql',
{ websocket: true },
makeHandler(
// from the previous step
{ schema, roots },
),
);
fastify.listen(4000, (err) => {
if (err) {
fastify.log.error(err);
return process.exit(1);
}
console.log('Listening to port 4000');
});
```
=> feat(server): Use `fastify-websocket`

src/client.ts
Might save someone a few seconds :wink:
=> refactor(client): add hint when missing WebSocket impl for Node

docs/interfaces/client.ClientOptions.md, docs/interfaces/server.Context.md, docs/interfaces/server.ServerOptions.md, docs/modules/client.md, docs/modules/common.md, docs/modules/server.md, docs/modules/use_fastify_websocket.md, docs/modules/use_uWebSockets.md, docs/modules/use_ws.md, src/__tests__/utils/tservers.ts, src/client.ts, src/server.ts, src/use/fastify-websocket.ts, src/use/uWebSockets.ts, src/use/ws.ts
=> feat: TypeScript generic for connection init payload (`connectionParams`)

README.md
Part of https://github.com/enisdenjo/graphql-ws/issues/325
=> Add Apollo Kotlin recipe to the README

README.md
=> Add Apollo iOS recipe to the README

src/__tests__/use.ts, src/use/@fastify/websocket.ts, src/use/uWebSockets.ts, src/use/ws.ts
=> fix(ws,uWebSockets,@fastify/websocket): Handle internal errors that are not instances of `Error`

.github/workflows/benchmark.yml, benchmark/servers/bun.ts, benchmark/servers/ports.mjs, package.json, scripts/post-gendocs.mjs, src/use/bun.ts, website/src/pages/get-started.mdx, yarn.lock
=> feat(server): Use Bun

.github/workflows/benchmark.yml, benchmark/servers/deno.ts, benchmark/servers/ports.mjs, benchmark/servers/schema.mjs, package.json, src/use/deno.ts, website/src/pages/get-started.mdx
=> feat(server): Use Deno

src/server.ts
There are some very small fixes to comments on the server.ts file
=> fix(server): typos in comments

src/use/bun.ts, src/use/deno.ts, website/src/pages/get-started.mdx, website/src/pages/recipes.mdx
=> Update documentation for v6 release

.changeset/itchy-hounds-remain.md, .changeset/little-toes-cheer.md, package.json
Closes https://github.com/enisdenjo/graphql-ws/issues/617#issuecomment-2595465578
=> Define exports for CommonJS TypeScript definitions in package.json
