enisdenjo/graphql-ws

PROTOCOL.md
package.json

- **Socket** is the main WebSocket communication channel between the _server_ and the _client_
- **Connection** is a connection **within the established socket** describing a "connection" through which the operation requests will be communicated
The WebSocket sub-protocol for this specification is: `graphql-transport-ws`
Messages are represented through the JSON structure and are stringified before being sent over the network. They are bidirectional, meaning both the server and the client conform to the specified message structure.
**All** messages contain the `type` field outlining the type or action this message describes. Depending on the type, the message can contain two more _optional_ fields:
- `id` used for uniquely identifying server responses and connecting them with the client …

GraphQL over WebSocket Protocol

---

PROTOCOL.md
src/server.ts
src/tests/server.ts

Closes: #10 
Implemented server-side pinging **only**. Pong messages are automatically sent in response to ping messages as required by the spec, meaning - this feature is a mandatory built-in, all browsers that don't support Ping and Pong are not RFC6455 compliant.
On the side note, there is no way to detect if Ping and Pong is supported through browser's JavaScript. Incompatible browsers will simply be kicked out after the keep-alive timeout.

feat: WebSocket Ping and Pong as keep-alive

---

README.md
src/client.ts
src/tests/client.ts

Following [The Observable Contract](http://reactivex.io/documentation/contract.html), both `OnError` and `OnComplete` notifications indicate that there will be no more emitted events. Having said that, the subscription should be disposed on these end notifications.

fix(client): Dispose of subscription on complete or error messages

---

PROTOCOL.md
src/server.ts
src/tests/server.ts

This PR adds supporting the changes of https://github.com/graphql/graphql-js/pull/2319 ([but also for allowing to use graphql-transport-ws with my live query implementation](https://github.com/n1ru4l/graphql-live-queries/blob/a4ce5ac727a7c44fd205b824d678db7717abd220/packages/in-memory-live-query-store/src/InMemoryLiveQueryStore.ts#L96-L103))
@enisdenjo Please let me know your opinion on adding this 😄

feat(server): Support returning multiple results from `execute`

---

package.json

I don't think we need to make sure the user is using a specific version of yarn
this was causing some trouble for us

fix: yarn engine is not required

---

src/tests/fixtures/simple.ts
src/tests/server.ts

Closes #29, closes #32
A few takeaways:
- Guaranteed shutdown of the server between tests. I've been naively simply using the `server.close()` function which actually [stops the server from accepting new connections and keeps existing connections](https://nodejs.org/api/net.html#net_server_close_callback)
- Super simple testing client

refactor(server): Stabilize and simplify tests

---

PROTOCOL.md
README.md
docs/interfaces/_server_.serveroptions.md
docs/modules/_message_.md
docs/modules/_server_.md
src/message.ts
src/server.ts
src/tests/client.ts
src/tests/server.ts
src/utils.ts

Closes #37, re-closes #27 and helps with #39
This PR comes along with some worthwhile breaking changes. One key change is trusting the execution arguments returned from the `onSubscribe` callback implicitly. This allows for all sorts of enhancements, some of them being:
- Persisted queries (has recipe)
- Increased validation process customisability (has recipe)
- Performance optimisations with custom subscription handling
- `onSubscribe` now executes _before_ any other subscribe message processing
- `onSubscribe` now takes 2 arguments, the context and the subscribe message
- `onSubscribe` now returns nothing,`ExecutionArgs` or an array of `GraphQLError`s
- Returning `void` (or nothing) will leave the execution args preparation and validation to the library
- Returned `ExecutionArgs` will …

feat(server): More callbacks, clearer differences and higher extensibility

---

CHANGELOG.md
CONTRIBUTING.md
README.md
docs/README.md
docs/enums/_message_.messagetype.md
docs/interfaces/_client_.client.md
docs/interfaces/_client_.clientoptions.md
docs/interfaces/_message_.completemessage.md
docs/interfaces/_message_.connectionackmessage.md
docs/interfaces/_message_.connectioninitmessage.md
docs/interfaces/_message_.errormessage.md
docs/interfaces/_message_.nextmessage.md
docs/interfaces/_message_.subscribemessage.md
docs/interfaces/_message_.subscribepayload.md
docs/interfaces/_server_.context.md
docs/interfaces/_server_.server.md
docs/interfaces/_server_.serveroptions.md
docs/interfaces/_types_.disposable.md
docs/interfaces/_types_.sink.md
docs/modules/_client_.md
docs/modules/_message_.md
docs/modules/_protocol_.md
docs/modules/_server_.md
docs/modules/_types_.md
package.json
yarn.lock

Aiming towards simplicity, this PR proposes renaming the library from `graphql-transport-ws` to `graphql-ws`. The old package will be deprecated and all versions as of v1 will be ported to the new name.

refactor: Rename to `graphql-ws`

---

README.md
docs/interfaces/_server_.serveroptions.md
docs/modules/_server_.md
src/server.ts
src/tests/server.ts

Inspired by https://github.com/enisdenjo/graphql-ws/issues/36#issuecomment-721095047
Helpful for when you want a dynamic context, but you want to avoid using the `onSubscribe` because you have to set the complete execution arguments up.

feat(server): For dynamic usage, `context` option can be a function too

---

PROTOCOL.md
README.md
src/message.ts
src/server.ts
src/tests/server.ts

Closes #44
Because of parity with HTTP conventions and reasons such as:
- Size _(the serialised `Document` object can be much bigger than a simple query)_
- Security _(no objects allowed through the `query` field, must provide parsable query)_
- Implementation independent _(#44)_
it might make sense to strictly require the `query` field to be of a string type.
However, there are reasons where we want to support the `Document` object too:
- ~~Performance _(you might have a ready `Document` to be sent from the client to avoid query parsing altogether)_~~ negligible
- You might want to use [`graphql-tag`](https://github.com/apollographql/graphql-tag) and get tooling support _(like from Prettier or syntax highlighting)_
- You use the [Apollo Client GraphQLRequest …

feat: `Subscribe` message query must be a string

---

src/server.ts

The previous logic here had `socket.protocol === undefined || socket.protocol !== GRAPHQL_TRANSPORT_WS_PROTOCOL` which was redundant (`undefined !== GRAPHQL_TRANSPORT_WS_PROTOCOL`), and further had `|| (Array.isArray(...) && ...)` which would never be evaluated since any array would be shortcut by the `socket.protocol !== GRAPHQL_TRANSPORT_WS_PROTOCOL` check. I believe this PR changes the logic to what was intended.

refactor: support array of protocols

---

src/utils.ts

We call the various `hasOwnProperty` helpers a lot; this PR reduces the number of prototype traversals used at runtime. It has no measurable performance impact on V8 unless `Object.prototype` has been tampered with, and even then the difference is negligible. But it does reduce lines of code :man_shrugging:
Feel free to close this, it brings little value and is mostly just personal preference.
<details>
<summary>Benchmark code</summary>
Run with `node --expose-gc perf.js`; benchmark based on: https://benediktmeurer.de/2017/09/07/restoring-for-in-peak-performance/
Results:
```
forInHasOwnPropertySafeDeref: 22874 ms.
forInHasOwnPropertySafe: 23460 ms.
forInSumSafeDeref: 26776 ms.
forInSumSafe: 26874 ms.
```
Interpretation: dereferenced version is 2.5% or 0.4% faster.
```js
if (typeof …
```

perf: reduces runtime prototype traversal for hasOwnProperty

---

src/server.ts

I believe `Object.values` is supported everywhere than `Object.entries` is supported.

refactor: use Object.values instead of .entries

---

docs/interfaces/_server_.serveroptions.md
docs/modules/_server_.md
src/server.ts
src/tests/server.ts

Previously we had:
- rootValue is only overwritten if onSubscribe didn't return anything
- context is overwritten if onSubscribe didn't return anything OR if onSubscribe's return value doesn't state context.
This PR makes this behaviour consistent by replacing the `rootValue` condition with:
- rootValue is overwritten if onSubscribe didn't return anything OR if onSubscribe's return value doesn't state rootValue
It also adjusts the check such that a user returning `contextValue: null` or `rootValue: null` (or anything else falsy) from `onSubscribe` will not have those values overwritten.

fix(server): Consistently set `rootValue` and `contextValue`, if not overridden

---

src/server.ts

This is for consistency with https://github.com/enisdenjo/graphql-ws/blob/5cc9770c60069159feea9be993bccd71c9ce8485/src/server.ts#L427-L430 - I'm not sure if that's desired or if these errors are safe to emit. If they are safe to emit, then a comment stating such would be good :+1:

fix: don't surface error details in production

---

src/server.ts
src/tests/server.ts

At the moment an empty array, or an array of things that don't match the error requirements, will be interpreted as `execArgs` which'll then cause all property references to be null and to have confusing errors thrown. This change handles the case where an array is returned but it doesn't match the requirements for an error array.
I'm not sure if emitting the error like this is the best route?

fix(server): Close socket if `onSubscribe` returns invalid array

---

src/server.ts
src/tests/server.ts

At the moment if the `'error'` handler for one of the clients were to throw then the `'error'` event won't be passed on to any further clients. This is probably not desired? I've wrapped it with a `try/catch` to allow the additional clients to be warned. However, I'm not happy with discarding the error here - we should raise it somehow. We could do something like `let firstError = null`; store the error to firstError in the catch, and then throw if firstError exists... Or we could log... Or... What do you want to do here?

fix(server): Distribute server error to all clients even if one error listener throws

---

README.md

This adds an example for using apollo-server-express with graphql-ws as a subscription layer.

docs(recipe): add example for apollo-server-express

---

src/client.ts
src/server.ts
src/tests/client.ts
src/tests/fixtures/simple.ts
src/tests/server.ts

@enisdenjo  I noticed that the client logic was sending a Complete event back to server immediately after the Server had sent a Complete event for that same operation, so hopefully this is a valid change.

fix: Stop sending messages after receiving complete

---

src/client.ts

fix(client): One cleanup per subscription

---

docs/interfaces/_client_.clientoptions.md
docs/modules/_client_.md
src/client.ts
src/tests/client.ts
src/tests/fixtures/simple.ts

Closes: #70 
**Beware:** if you decide to return a promise, [the server might kick you off if it takes too long to resolve](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#connectioninit)! You can either tune the promise or control the [server `connectionInitWaitTimeout`](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/_server_.serveroptions.md#connectioninitwaittimeout).

feat(client): `connectionParams` may return a promise

---

README.md
docs/interfaces/_client_.clientoptions.md
src/client.ts
src/tests/client.ts

Closes: #80 
Client `retryTimeout` option has been replaced with the new `retryWait`. It allows you to control the retry timeout strategy by resolving the returned promise when ready. The default implement the randomised exponential backoff like so:
```ts
// this is the default
const retryWait = async function randomisedExponentialBackoff(retries: number) {
let retryDelay = 1000; // start with 1s delay
for (let i = 0; i < retries; i++) {
retryDelay *= 2; // square `retries` times
}
await new Promise((resolve) =>
setTimeout(
// resolve pending promise with added random timeout from 300ms to 3s
resolve,
retryDelay + Math.floor(Math.random() * (3000 - 300) + 300),
),
);
};
```

feat(client): Retry with randomised exponential backoff or provide your own strategy

---

PROTOCOL.md
docs/interfaces/_server_.context.md
src/server.ts
src/tests/server.ts

Closes: #95
The `Context.subscriptions` record can hold either an `AsyncIterator` or `Promise` value.

fix(server): Enforce ID uniqueness across all operations and during the whole subscription life

---

docs/interfaces/_server_.server.md
docs/interfaces/_server_.serveroptions.md
docs/interfaces/_server_.websocket.md
src/server.ts
src/tests/server.ts
src/use/ws.ts

Closes: #91
The return function of `server.opened` (`closed`) now requires the close event code and reason for reporting to the `onDisconnect` callback.

feat(server): Add `onDisconnect` callback

---

docs/interfaces/client.clientoptions.md
src/client.ts
src/tests/client.ts

Closes: #122
Introduces a new, optional, `isFatalConnectionProblem(errOrCloseEvent: unknown): boolean` client option for giving the user power to decide if the client should retry.
By default all non close events fatal.
**Beware**, the following close events are fatal regardless:
- `1002: Protocol Error`
- `1011: Internal Error`
- `4400: Bad Request`
- `4401: Unauthorized` _tried subscribing before connect ack_
- `4409: Subscriber for <id> already exists` _distinction is very important_
- `4429: Too many initialisation requests`

feat(client): `isFatalConnectionProblem` option for deciding if the connect error should be immediately reported or the connection retried

---

src/client.ts
src/tests/client.ts

fix(client): New `error` event listener for handling connection errors

---

docs/interfaces/client.clientoptions.md
src/client.ts
src/tests/client.ts

Closes #145, closes #146 
Updated `url` in `ClientOptions` to support function type that returns a Promise, the same way as `connectionParams`. The use case is that it can be used together with automatic reconnect on abnormal socket closure such that the url can be dynamically changing each time it reconnects.
Our specific use case: we have a service that checks the csrf token as part of the query string, so we have to add the csrf token to the `url`. The token might expire, and in that case, we would like to take advantage of the automatic reconnect functionality to be able to dynamically pick up an updated csrf token, and this can be achieved with a function that returns a Promise.
Specifically, we'd like to use it as:
`createClient({
url: () => new Promise((resolve) => { …

feat(client): `url` option accepts a function or a Promise

---

README.md
docs/interfaces/server.serveroptions.md
src/server.ts
src/tests/fixtures/simple.ts
src/tests/server.ts

Closes #127
Accept a function for the `schema` option that will be called on every subscription request allowing you to manipulate the schema dynamically.
Throwing an error from within this function will close the socket with the `Error` message in the close event reason.

feat(server): Dynamic `schema` support by accepting a function or a Promise

---

README.md
docs/interfaces/server.serveroptions.md
src/server.ts
src/tests/fixtures/simple.ts

`graphql` is already a peer dependency, no need to force the user to supply it.
```diff
- import { execute, subscribe } from 'graphql';
import { makeServer } from 'graphql-ws';
import { schema } from './my-graphql';
const server = makeServer({
schema,
-  execute,
-  subscribe,
});
```

feat(server): `execute` and `subscribe` are optional

---

src/client.ts

If client is used for a lot of simultaneous subscription, ther's unnecessary overload due to check MessageType and id for every subscription handler

perf(client): Focus subscription message listeners on `id`

---

docs/interfaces/client.clientoptions.md
docs/interfaces/server.serveroptions.md
docs/modules/client.md
docs/modules/common.md
src/client.ts
src/common.ts
src/server.ts
src/tests/client.ts
src/tests/fixtures/simple.ts
src/tests/server.ts

If you want to use a fancier types inside your JSON over the websocket like bigints or dates, it's handy to be able to control the stringification and unstringifiation of the messages going across this socket! This adds options to the server to allow overriding the `revive` and `replace` functions the server uses in JSON.stringify and JSON.parse so userland can hook in and alter the behaviour. We stay compatible with the graphql-ws protocol by sticking with JSON but still allow flexibility to marshal fancier types to and from JSON easily.

feat: Support custom JSON message `reviver` and `replacer`

---

README.md

Closes #177 
When importing from `@apollo/client` a dependency to react is introduced. Hence the sample recipes do not work when used with eg `apollo-angular`.  Importing from `@apollo/client/core` has no `react` deps and hence works with all frontend frameworks (incl. react).

docs(recipe): import Apollo observable from core to avoid React dependency

---

README.md

All code snippets in README.md used wss:// as protocol insead of ws://
I find way more useful providing code snippets that work in a test environment without a certificate setup than examples for production environments. With this approach, users can try out the library more easily.

docs: use port 4000 and drop tls for clarity

---

README.md
docs/interfaces/use_uwebsockets.extra.md
docs/interfaces/use_uwebsockets.persistedrequest.md
docs/interfaces/use_uwebsockets.upgradedata.md
docs/modules/use_uwebsockets.md
src/tests/use.ts
src/use/uWebSockets.ts

Due to [this limitation](https://github.com/uNetworking/uWebSockets.js/discussions/84) (for performance optimizations), we can't use [uWS.HttpRequest ](https://unetworking.github.io/uWebSockets.js/generated/interfaces/httprequest.html) out of  scope of `upgrade` callback, and it wasn't possible to get some headers from `upgradeReq`.

feat(uWebSockets): Add `persistedRequest` to context extra and deprecate uWS's stack allocated `request`

---

PROTOCOL.md
README.md
docs/enums/common.messagetype.md
docs/interfaces/client.clientoptions.md
docs/interfaces/common.pingmessage.md
docs/interfaces/common.pongmessage.md
docs/modules/client.md
docs/modules/common.md
src/client.ts
src/common.ts
src/server.ts
src/tests/client.ts
src/tests/server.ts
src/tests/utils/tservers.ts

Closes #117
Introduces bidirectional ping/pong messages both in the Protocol and in the implementation. Server will respond with a pong to a ping, the same way a client would.
A simple recipe showcasing a client that times out if no pong is received and measures latency, looks like this:
```js
import { createClient } from 'graphql-ws';
let activeSocket,
timedOut,
pingSentAt = 0,
latency = 0;
createClient({
url: 'ws://i.time.out:4000/and-measure/latency',
keepAlive: 10_000, // ping server every 10 seconds
on: {
connected: (socket) => (activeSocket = socket),
ping: (received) => {
if (!received /* sent */) {
pingSentAt = Date.now();
timedOut = setTimeout(() => {
if (activeSocket.readyState === WebSocket.OPEN)
activeSocket.close(4408, 'Request Timeout');
}, 5_000); // wait 5 seconds for the …
```

feat: Bidirectional ping/pong message types

---

README.md

$ is not necessary for for the install snippet

docs: remove $ from yarn add

---

docs/enums/common.CloseCode.md
docs/interfaces/client.ClientOptions.md
src/__tests__/client.ts
src/__tests__/utils/tservers.ts
src/client.ts
src/common.ts

On the server side exists a `connectionInitWaitTimeout` that would close the connection if no init is received but it doesn't exist the other way around. It could happen that the socket connects to an instance that is overloaded or shutting down and is not responding to messages or at least super slowly. In that case, the client should also timeout and try to reconnect and retry connection initialisation.
I added the same logic there's on the sevrer side but with a `connectionAckWaitTimeout` parameter. A 0/Infinity/null/empty value will not trigger the timeout. A positive number value will trigger a timeout that will close the socket with a specific error code and message. The timeout clears upon receiving the connection ack itself  Defaults to 0 to prevent breaking changes.

feat(client): Add `connectionAckWaitTimeout` option

---

README.md

- Apollo Client Web: new section for using built-in support; update
project name; more precise doc link
- Apollo Server: proper shutdown behavior; don't listen until server is
ready; more precise doc link
- new section documenting Apollo Studio Explorer and GraphiQL IDE support
Part of #325.

README: Update Apollo and related sections

---

package.json

This puts the `"types"` of every export in `package.json` to be the first entry in the object. Without this, import resolution fails in `nodenext` and `node16` modes.

fix: reorder types in package.json exports

---

README.md

NodeJS provides a randomUUID method since the version 14.17 and 15.6.

docs: modernise nodejs example

---

PROTOCOL.md
src/__tests__/__snapshots__/common.ts.snap
src/__tests__/common.ts
src/common.ts

Closes #455
Related https://github.com/graphql/graphql-over-http/pull/243
Original thinking was to support keeping the message size small by completely omitting the payload if nullish. But, that was an unnecessary limiting optimization.
Furthermore, allowing null values also keeps the spec more in line with the GraphQL over HTTP spec.
> Specifying `null` in JSON (or equivalent values in other formats) as values for optional request parameters is equivalent to not specifying them at all.
[_GraphQL over HTTP spec_](https://graphql.github.io/graphql-over-http/draft/)

feat: Allow null payloads in messages

---

PROTOCOL.md

Closes #455 
EDIT by @enisdenjo: [Use the "closes" syntax instead.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

Add information about rejecting a connection.

---

website/src/pages/recipes.mdx

Hi, I updated the example for using `urql`, because the current example is not valid for the latest `urql` package.
* move `import { defaultExchanges }` to `import { cacheExchange, fetchExchange }`
* `defaultExchanges` are removed in the latest package. ([CHANGELOG link](https://github.com/urql-graphql/urql/blob/35657e771633be43b850f0a1f7fdbac94b075dd7/packages/core/CHANGELOG.md#major-changes))
* Type assertion for client.subscribe
* The argument for `forwardSubscription` returned non-nullable string `query` in previous packages, ([related link](https://github.com/urql-graphql/urql/blob/%40urql/vue%401.0.4/packages/core/src/exchanges/subscription.ts#L43))
* But it does return a nullable `query` now. ([related link #1](https://github.com/urql-graphql/urql/blob/main/packages/core/src/exchang …

docs(recipe): update urql example to fit on latest version

---

website/src/pages/get-started.mdx

- Fixes a typo of the Bun import in the Getting Started docs
- Changes `graphql-ws/lib/use/lib/bun` to `graphql-ws/lib/use/bun` ✏️

docs(bun): Fix Bun Import

---

src/__tests__/server.ts
src/server.ts

fix(server): Acknowledge connection before notifying the client to avoid race conditions with slow sends

---

PROTOCOL.md

This PR aims to clarify the section of the protocol which states that the `id` field is optional even though this field is either required or not present as per the type definitions. (Also discussed in [#340](https://github.com/enisdenjo/graphql-ws/discussions/340#discussioncomment-7703620))
At first, I wanted to mention specifically that `Subscribe`, `Next`, `Error`, and `Complete` message types needs to have the `id` field. However, the sentence that needs to be clarified is in the "Communication" section which comes before the explanation of the message types. So, I used the term "Messages corresponding to operations" to refer to those message types. 
Though, I am not sure if this sentence sounds clear enough. I am happy to accept any improvements for wording.

docs(protocol): clarify id field is not optional

---

src/client.ts

This adds retry info to the connecting and connected events. This helps us give the user better status about the current state of their network connection with the websocket.

Add retry info to connect events

---

src/server.ts

Follow-up to https://github.com/enisdenjo/graphql-ws/commit/6ae6e6f4e392975ad786cf61e4947fd57f5cf56c, which missed the `close` method

fix(server): Close code and reason are optional for `close`

---

src/use/ws.ts

WS library has changed how types are exported and graphql-ws is breaking builds if type checking for libraries is active:
```
node_modules/graphql-ws/lib/use/ws.d.ts(5,28): error TS2339: Property 'prototype' does not exist on type 'typeof import("/ptp/node_modules/@types/ws/index")'.
node_modules/graphql-ws/lib/use/ws.d.ts(6,27): error TS2694: Namespace '"/ptp/node_modules/@types/ws/index"' has no exported member 'Server'.
```
I have just properly imported types so we can use the library without problems. 
Let me know if you need anything else from me. Hope to see it released soon!

Fix WS types, current ones are broken

---

.changeset/eleven-bears-warn.md
src/common.ts

https://github.com/enisdenjo/graphql-ws/releases/tag/v6.0.0 introduced a `FormattedExecutionResult`, however, its `errors` type seems to be incorrect as it's set to `ReadonlyArray<FormattedExecutionResult>` rather than `ReadonlyArray<GraphQLFormattedError>`:
```ts
/** @category Common */
export interface FormattedExecutionResult<
Data = Record<string, unknown>,
Extensions = Record<string, unknown>,
> {
errors?: ReadonlyArray<FormattedExecutionResult> | undefined;
data?: Data | null | undefined;
hasNext?: boolean | undefined;
extensions?: Extensions | undefined;
}
```
This is remediated by this PR.

fix(common): Fix the `FormattedExecutionResult.errors` type
